import type {
  ExecutionEvent,
  ExecutionRun,
  TraceFixture,
  TraceId,
} from "@one-prompt/shared";
import { DEFAULT_PROMPT, DEMO_TRACE_IDS } from "@one-prompt/shared";

type EventDef = Omit<ExecutionEvent, "runId" | "sequence"> & { seq: number };

function buildRun(id: string, label: string, result: ExecutionRun["result"]): ExecutionRun {
  return {
    id,
    label,
    prompt: DEFAULT_PROMPT,
    source: "replay",
    status: "completed",
    createdAt: "2026-07-10T18:00:00.000Z",
    startedAt: "2026-07-10T18:00:01.000Z",
    completedAt: "2026-07-10T18:01:15.000Z",
    currentSequence: 0,
    result,
  };
}

function toEvents(runId: string, defs: EventDef[]): ExecutionEvent[] {
  return defs.map((d) => {
    const { seq, ...rest } = d;
    return { ...rest, runId, sequence: seq };
  });
}

const SHARED_START: EventDef[] = [
  {
    id: "evt-prompt",
    seq: 1,
    logicalTaskId: "prompt",
    dependencyIds: [],
    kind: "prompt",
    status: "succeeded",
    title: "Prompt received",
    description: "One instruction entered the system.",
    relativeStartMs: 0,
    durationMs: 400,
    attempt: 1,
    phase: "intake",
    lane: "main",
  },
  {
    id: "evt-plan",
    seq: 2,
    parentId: "evt-prompt",
    logicalTaskId: "plan",
    dependencyIds: ["evt-prompt"],
    kind: "plan",
    status: "succeeded",
    title: "Building execution plan",
    description: "Decomposing the checkout investigation into inspect, reproduce, fix, deploy, and verify phases.",
    relativeStartMs: 500,
    durationMs: 2200,
    attempt: 1,
    phase: "planning",
    lane: "main",
    model: { provider: "scripted", model: "planner-v1", inputTokens: 420, outputTokens: 180 },
  },
  {
    id: "evt-inspect-service",
    seq: 3,
    parentId: "evt-plan",
    logicalTaskId: "inspect-service",
    dependencyIds: ["evt-plan"],
    kind: "tool",
    status: "succeeded",
    title: "Inspect checkout service",
    description: "Reading service configuration and entry points for order creation.",
    relativeStartMs: 3000,
    durationMs: 1800,
    attempt: 1,
    phase: "investigation",
    lane: "main",
    tool: { name: "service_inspector", operation: "read_config" },
  },
];

function buildCleanTrace(): TraceFixture {
  const runId = DEMO_TRACE_IDS.clean;
  const events = toEvents(runId, [
    ...SHARED_START,
    {
      id: "evt-search-retry",
      seq: 4,
      parentId: "evt-inspect-service",
      logicalTaskId: "search-retry",
      dependencyIds: ["evt-inspect-service"],
      kind: "search",
      status: "succeeded",
      title: "Search retry configuration",
      description: "Finding workflow retry policies and notification handlers.",
      relativeStartMs: 5000,
      durationMs: 2400,
      attempt: 1,
      phase: "investigation",
      lane: "main",
      tool: { name: "repo_search", operation: "grep" },
    },
    {
      id: "evt-inspect-order",
      seq: 5,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-order",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Inspect order creation logic",
      description: "Tracing the code path that persists orders on checkout completion.",
      relativeStartMs: 5200,
      durationMs: 3200,
      attempt: 1,
      phase: "investigation",
      lane: "branch-a",
      branchId: "parallel-investigation",
      tool: { name: "code_reader", operation: "open_file" },
    },
    {
      id: "evt-inspect-tests",
      seq: 6,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-tests",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Read relevant tests",
      description: "Reviewing checkout and retry test coverage.",
      relativeStartMs: 5400,
      durationMs: 2800,
      attempt: 1,
      phase: "investigation",
      lane: "branch-b",
      branchId: "parallel-investigation",
      tool: { name: "test_reader", operation: "list_tests" },
    },
    {
      id: "evt-hypothesis",
      seq: 7,
      parentId: "evt-search-retry",
      logicalTaskId: "hypothesis",
      dependencyIds: ["evt-search-retry", "evt-inspect-order", "evt-inspect-tests"],
      kind: "model",
      status: "succeeded",
      title: "Form hypothesis",
      description: "Request-level retries may repeat order creation without an idempotency guard.",
      relativeStartMs: 9000,
      durationMs: 2000,
      attempt: 1,
      phase: "analysis",
      lane: "main",
      model: { provider: "scripted", model: "analyst-v1", inputTokens: 2100, outputTokens: 340 },
    },
    {
      id: "evt-reproduce",
      seq: 8,
      parentId: "evt-hypothesis",
      logicalTaskId: "reproduce",
      dependencyIds: ["evt-hypothesis"],
      kind: "test",
      status: "succeeded",
      title: "Reproduce duplicate-order behavior",
      description: "Repeating checkout with the same event ID to confirm a second order is created.",
      relativeStartMs: 11500,
      durationMs: 4500,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-propose-fix",
      seq: 9,
      parentId: "evt-reproduce",
      logicalTaskId: "propose-fix",
      dependencyIds: ["evt-reproduce"],
      kind: "model",
      status: "succeeded",
      title: "Propose idempotency guard",
      description: "Deduplicate order creation by event ID and isolate notification retries.",
      relativeStartMs: 16500,
      durationMs: 2500,
      attempt: 1,
      phase: "fix",
      lane: "main",
      model: { provider: "scripted", model: "analyst-v1", inputTokens: 1800, outputTokens: 420 },
    },
    {
      id: "evt-apply-patch",
      seq: 10,
      parentId: "evt-propose-fix",
      logicalTaskId: "apply-patch",
      dependencyIds: ["evt-propose-fix"],
      kind: "write",
      status: "succeeded",
      title: "Apply patch",
      description: "Adding idempotency key check before order persistence.",
      relativeStartMs: 19500,
      durationMs: 3000,
      attempt: 1,
      phase: "fix",
      lane: "main",
      sideEffect: {
        type: "repository",
        occurred: true,
        safeToRetry: true,
        strategy: "Branch-scoped commit",
      },
    },
    {
      id: "evt-run-tests",
      seq: 11,
      parentId: "evt-apply-patch",
      logicalTaskId: "run-tests",
      dependencyIds: ["evt-apply-patch"],
      kind: "test",
      status: "succeeded",
      title: "Run checkout tests",
      description: "All checkout and retry tests pass.",
      relativeStartMs: 23000,
      durationMs: 5000,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-deploy",
      seq: 12,
      parentId: "evt-run-tests",
      logicalTaskId: "deploy",
      dependencyIds: ["evt-run-tests"],
      kind: "deployment",
      status: "succeeded",
      title: "Deploy preview on Render",
      description: "Creating preview deployment for checkout service.",
      relativeStartMs: 28500,
      durationMs: 8000,
      attempt: 1,
      phase: "deploy",
      lane: "main",
      sideEffect: {
        type: "deployment",
        occurred: true,
        safeToRetry: true,
        strategy: "Unique deployment request ID",
        idempotencyKey: "deploy-preview-checkout-42",
      },
      deployment: {
        provider: "render",
        service: "checkout-api",
        environment: "preview",
        status: "live",
        url: "https://checkout-api-preview.onrender.com",
      },
    },
    {
      id: "evt-verify",
      seq: 13,
      parentId: "evt-deploy",
      logicalTaskId: "verify",
      dependencyIds: ["evt-deploy"],
      kind: "test",
      status: "succeeded",
      title: "Verify behavior",
      description: "Repeated requests produced one order on preview.",
      relativeStartMs: 37000,
      durationMs: 4000,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-result",
      seq: 14,
      parentId: "evt-verify",
      logicalTaskId: "result",
      dependencyIds: ["evt-verify"],
      kind: "result",
      status: "succeeded",
      title: "Investigation complete",
      description: "Duplicate-order cause identified and verified.",
      relativeStartMs: 41500,
      durationMs: 800,
      attempt: 1,
      phase: "complete",
      lane: "main",
    },
  ]);

  return {
    run: buildRun(runId, "Clean path", {
      status: "success",
      title: "Duplicate-order cause identified and verified",
      summary: "Request-level retries repeated order creation without an idempotency guard.",
      cause: "Request-level retries repeated an order-creation side effect without an idempotency guard.",
      fix: "Separate retryable notification work and deduplicate order creation by event ID.",
      verification: "Repeated requests produced one order.",
    }),
    events,
  };
}

function buildDetourTrace(): TraceFixture {
  const runId = DEMO_TRACE_IDS.detour;
  const events = toEvents(runId, [
    ...SHARED_START,
    {
      id: "evt-inspect-payment",
      seq: 4,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-payment",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Inspect payment authorization",
      description: "Initial hypothesis: duplicate charges from payment retries.",
      relativeStartMs: 5000,
      durationMs: 3500,
      attempt: 1,
      phase: "investigation",
      lane: "main",
      tool: { name: "code_reader", operation: "open_file" },
    },
    {
      id: "evt-wait-payment-api",
      seq: 5,
      parentId: "evt-inspect-payment",
      logicalTaskId: "wait-payment",
      dependencyIds: ["evt-inspect-payment"],
      kind: "wait",
      status: "succeeded",
      title: "Wait for payment sandbox",
      description: "Waiting on irrelevant sandbox tool result.",
      relativeStartMs: 8800,
      durationMs: 4000,
      attempt: 1,
      phase: "investigation",
      lane: "main",
    },
    {
      id: "evt-search-retry",
      seq: 6,
      parentId: "evt-wait-payment-api",
      logicalTaskId: "search-retry",
      dependencyIds: ["evt-wait-payment-api"],
      kind: "search",
      status: "succeeded",
      title: "Search retry configuration",
      description: "Payment path ruled out. Searching workflow retry policies.",
      relativeStartMs: 13000,
      durationMs: 2800,
      attempt: 1,
      phase: "investigation",
      lane: "main",
      tool: { name: "repo_search", operation: "grep" },
    },
    {
      id: "evt-inspect-order",
      seq: 7,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-order",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Inspect order creation logic",
      description: "Tracing order persistence on checkout completion.",
      relativeStartMs: 5200,
      durationMs: 3200,
      attempt: 1,
      phase: "investigation",
      lane: "branch-a",
      branchId: "parallel-investigation",
      tool: { name: "code_reader", operation: "open_file" },
    },
    {
      id: "evt-inspect-tests",
      seq: 8,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-tests",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Read relevant tests",
      description: "Reviewing checkout and retry test coverage.",
      relativeStartMs: 5400,
      durationMs: 2800,
      attempt: 1,
      phase: "investigation",
      lane: "branch-b",
      branchId: "parallel-investigation",
      tool: { name: "test_reader", operation: "list_tests" },
    },
    {
      id: "evt-hypothesis-corrected",
      seq: 9,
      parentId: "evt-search-retry",
      logicalTaskId: "hypothesis",
      dependencyIds: ["evt-search-retry", "evt-inspect-order", "evt-inspect-tests"],
      kind: "model",
      status: "succeeded",
      title: "Correct hypothesis",
      description: "Payment retries are idempotent. Order creation lacks an event ID guard.",
      relativeStartMs: 16200,
      durationMs: 2200,
      attempt: 1,
      phase: "analysis",
      lane: "main",
      model: { provider: "scripted", model: "analyst-v1", inputTokens: 2800, outputTokens: 380 },
    },
    {
      id: "evt-reproduce",
      seq: 10,
      parentId: "evt-hypothesis-corrected",
      logicalTaskId: "reproduce",
      dependencyIds: ["evt-hypothesis-corrected"],
      kind: "test",
      status: "succeeded",
      title: "Reproduce duplicate-order behavior",
      description: "Confirming duplicate orders from request-level retries.",
      relativeStartMs: 18800,
      durationMs: 4500,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-propose-fix",
      seq: 11,
      parentId: "evt-reproduce",
      logicalTaskId: "propose-fix",
      dependencyIds: ["evt-reproduce"],
      kind: "model",
      status: "succeeded",
      title: "Propose idempotency guard",
      description: "Deduplicate order creation by event ID.",
      relativeStartMs: 23800,
      durationMs: 2500,
      attempt: 1,
      phase: "fix",
      lane: "main",
      model: { provider: "scripted", model: "analyst-v1", inputTokens: 1900, outputTokens: 400 },
    },
    {
      id: "evt-apply-patch",
      seq: 12,
      parentId: "evt-propose-fix",
      logicalTaskId: "apply-patch",
      dependencyIds: ["evt-propose-fix"],
      kind: "write",
      status: "succeeded",
      title: "Apply patch",
      description: "Adding idempotency key check before order persistence.",
      relativeStartMs: 26800,
      durationMs: 3000,
      attempt: 1,
      phase: "fix",
      lane: "main",
      sideEffect: { type: "repository", occurred: true, safeToRetry: true },
    },
    {
      id: "evt-run-tests",
      seq: 13,
      parentId: "evt-apply-patch",
      logicalTaskId: "run-tests",
      dependencyIds: ["evt-apply-patch"],
      kind: "test",
      status: "succeeded",
      title: "Run checkout tests",
      description: "All tests pass.",
      relativeStartMs: 30300,
      durationMs: 5000,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-deploy",
      seq: 14,
      parentId: "evt-run-tests",
      logicalTaskId: "deploy",
      dependencyIds: ["evt-run-tests"],
      kind: "deployment",
      status: "succeeded",
      title: "Deploy preview on Render",
      description: "Creating preview deployment.",
      relativeStartMs: 35800,
      durationMs: 8000,
      attempt: 1,
      phase: "deploy",
      lane: "main",
      sideEffect: { type: "deployment", occurred: true, safeToRetry: true },
      deployment: {
        provider: "render",
        service: "checkout-api",
        environment: "preview",
        status: "live",
        url: "https://checkout-api-preview.onrender.com",
      },
    },
    {
      id: "evt-verify",
      seq: 15,
      parentId: "evt-deploy",
      logicalTaskId: "verify",
      dependencyIds: ["evt-deploy"],
      kind: "test",
      status: "succeeded",
      title: "Verify behavior",
      description: "Repeated requests produced one order.",
      relativeStartMs: 44300,
      durationMs: 4000,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-result",
      seq: 16,
      parentId: "evt-verify",
      logicalTaskId: "result",
      dependencyIds: ["evt-verify"],
      kind: "result",
      status: "succeeded",
      title: "Investigation complete",
      description: "Correct result via a more expensive route.",
      relativeStartMs: 48800,
      durationMs: 800,
      attempt: 1,
      phase: "complete",
      lane: "main",
    },
  ]);

  return {
    run: buildRun(runId, "Unexpected detour", {
      status: "success",
      title: "Duplicate-order cause identified and verified",
      summary: "Correct result after an unnecessary payment investigation branch.",
      cause: "Request-level retries repeated order creation without an idempotency guard.",
      fix: "Deduplicate order creation by event ID.",
      verification: "Repeated requests produced one order.",
    }),
    events,
  };
}

function buildLateFailureTrace(): TraceFixture {
  const runId = DEMO_TRACE_IDS["late-failure"];
  const events = toEvents(runId, [
    ...SHARED_START,
    {
      id: "evt-search-retry",
      seq: 4,
      parentId: "evt-inspect-service",
      logicalTaskId: "search-retry",
      dependencyIds: ["evt-inspect-service"],
      kind: "search",
      status: "succeeded",
      title: "Search retry configuration",
      description: "Finding workflow retry policies.",
      relativeStartMs: 5000,
      durationMs: 2400,
      attempt: 1,
      phase: "investigation",
      lane: "main",
      tool: { name: "repo_search", operation: "grep" },
    },
    {
      id: "evt-inspect-order",
      seq: 5,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-order",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Inspect order creation logic",
      description: "Tracing order persistence path.",
      relativeStartMs: 5200,
      durationMs: 3200,
      attempt: 1,
      phase: "investigation",
      lane: "branch-a",
      branchId: "parallel-investigation",
      tool: { name: "code_reader", operation: "open_file" },
    },
    {
      id: "evt-inspect-tests",
      seq: 6,
      parentId: "evt-inspect-service",
      logicalTaskId: "inspect-tests",
      dependencyIds: ["evt-inspect-service"],
      kind: "tool",
      status: "succeeded",
      title: "Read relevant tests",
      description: "Reviewing checkout test coverage.",
      relativeStartMs: 5400,
      durationMs: 2800,
      attempt: 1,
      phase: "investigation",
      lane: "branch-b",
      branchId: "parallel-investigation",
      tool: { name: "test_reader", operation: "list_tests" },
    },
    {
      id: "evt-hypothesis",
      seq: 7,
      parentId: "evt-search-retry",
      logicalTaskId: "hypothesis",
      dependencyIds: ["evt-search-retry", "evt-inspect-order", "evt-inspect-tests"],
      kind: "model",
      status: "succeeded",
      title: "Form hypothesis",
      description: "Request-level retries repeat order creation without idempotency guard.",
      relativeStartMs: 9000,
      durationMs: 2000,
      attempt: 1,
      phase: "analysis",
      lane: "main",
      model: { provider: "scripted", model: "analyst-v1", inputTokens: 2100, outputTokens: 340 },
    },
    {
      id: "evt-reproduce",
      seq: 8,
      parentId: "evt-hypothesis",
      logicalTaskId: "reproduce",
      dependencyIds: ["evt-hypothesis"],
      kind: "test",
      status: "succeeded",
      title: "Reproduce duplicate-order behavior",
      description: "Confirming duplicate orders from retries.",
      relativeStartMs: 11500,
      durationMs: 4500,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-propose-fix",
      seq: 9,
      parentId: "evt-reproduce",
      logicalTaskId: "propose-fix",
      dependencyIds: ["evt-reproduce"],
      kind: "model",
      status: "succeeded",
      title: "Propose idempotency guard",
      description: "Deduplicate order creation by event ID.",
      relativeStartMs: 16500,
      durationMs: 2500,
      attempt: 1,
      phase: "fix",
      lane: "main",
      model: { provider: "scripted", model: "analyst-v1", inputTokens: 1800, outputTokens: 420 },
    },
    {
      id: "evt-apply-patch",
      seq: 10,
      parentId: "evt-propose-fix",
      logicalTaskId: "apply-patch",
      dependencyIds: ["evt-propose-fix"],
      kind: "write",
      status: "succeeded",
      title: "Apply patch",
      description: "Adding idempotency key check.",
      relativeStartMs: 19500,
      durationMs: 3000,
      attempt: 1,
      phase: "fix",
      lane: "main",
      sideEffect: { type: "repository", occurred: true, safeToRetry: true },
    },
    {
      id: "evt-run-tests",
      seq: 11,
      parentId: "evt-apply-patch",
      logicalTaskId: "run-tests",
      dependencyIds: ["evt-apply-patch"],
      kind: "test",
      status: "succeeded",
      title: "Run checkout tests",
      description: "All tests pass.",
      relativeStartMs: 23000,
      durationMs: 5000,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-deploy",
      seq: 12,
      parentId: "evt-run-tests",
      logicalTaskId: "deploy",
      dependencyIds: ["evt-run-tests"],
      kind: "deployment",
      status: "succeeded",
      title: "Deploy preview on Render",
      description: "Creating preview deployment.",
      relativeStartMs: 28500,
      durationMs: 8000,
      attempt: 1,
      phase: "deploy",
      lane: "main",
      sideEffect: {
        type: "deployment",
        occurred: true,
        safeToRetry: true,
        idempotencyKey: "deploy-preview-checkout-42",
      },
      deployment: {
        provider: "render",
        service: "checkout-api",
        environment: "preview",
        status: "live",
        url: "https://checkout-api-preview.onrender.com",
      },
    },
    {
      id: "evt-checkpoint",
      seq: 13,
      parentId: "evt-deploy",
      logicalTaskId: "checkpoint",
      dependencyIds: ["evt-deploy"],
      kind: "checkpoint",
      status: "succeeded",
      title: "Preserving completed work",
      description: "Nine steps completed. Checkpoint before verification.",
      relativeStartMs: 36800,
      durationMs: 600,
      attempt: 1,
      phase: "checkpoint",
      lane: "main",
    },
    {
      id: "evt-verify-1",
      seq: 14,
      parentId: "evt-checkpoint",
      logicalTaskId: "verify",
      dependencyIds: ["evt-checkpoint"],
      kind: "test",
      status: "failed",
      title: "Verify behavior",
      description: "Preview health check timed out waiting for notification dependency.",
      relativeStartMs: 37600,
      durationMs: 6000,
      attempt: 1,
      maxAttempts: 2,
      phase: "verification",
      lane: "main",
      error: {
        name: "VerificationTimeout",
        message: "Notification dependency did not respond within 5s",
        retryable: true,
      },
    },
    {
      id: "evt-retry-marker",
      seq: 15,
      parentId: "evt-verify-1",
      logicalTaskId: "verify-retry",
      dependencyIds: ["evt-verify-1"],
      kind: "retry",
      status: "succeeded",
      title: "Retrying verification",
      description: "Retrying this step without restarting the investigation.",
      relativeStartMs: 43800,
      durationMs: 400,
      attempt: 1,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-verify-2",
      seq: 16,
      parentId: "evt-retry-marker",
      logicalTaskId: "verify",
      dependencyIds: ["evt-retry-marker"],
      kind: "test",
      status: "succeeded",
      title: "Verify behavior",
      description: "Repeated requests produced one order. No order side effect repeated.",
      relativeStartMs: 44400,
      durationMs: 4000,
      attempt: 2,
      maxAttempts: 2,
      phase: "verification",
      lane: "main",
    },
    {
      id: "evt-result",
      seq: 17,
      parentId: "evt-verify-2",
      logicalTaskId: "result",
      dependencyIds: ["evt-verify-2"],
      kind: "result",
      status: "succeeded",
      title: "Investigation complete",
      description: "Cause fixed after controlled verification failure.",
      relativeStartMs: 48700,
      durationMs: 800,
      attempt: 1,
      phase: "complete",
      lane: "main",
    },
  ]);

  return {
    run: buildRun(runId, "Late failure", {
      status: "success",
      title: "Duplicate-order cause identified and verified",
      summary: "Verification failed once. Retry succeeded without repeating prior side effects.",
      cause: "Request-level retries repeated order creation without an idempotency guard.",
      fix: "Separate retryable notification work and deduplicate order creation by event ID.",
      verification: "Repeated requests produced one order after retry.",
    }),
    events,
  };
}

const BUILDERS: Record<TraceId, () => TraceFixture> = {
  clean: buildCleanTrace,
  detour: buildDetourTrace,
  "late-failure": buildLateFailureTrace,
};

export function getTraceFixture(traceId: TraceId): TraceFixture {
  return BUILDERS[traceId]();
}

export function getAllTraceFixtures(): TraceFixture[] {
  return (Object.keys(BUILDERS) as TraceId[]).map((id) => BUILDERS[id]());
}

export function getTraceByRunId(runId: string): TraceFixture | null {
  const map: Record<string, TraceId> = {
    [DEMO_TRACE_IDS.clean]: "clean",
    [DEMO_TRACE_IDS.detour]: "detour",
    [DEMO_TRACE_IDS["late-failure"]]: "late-failure",
  };
  const traceId = map[runId];
  return traceId ? getTraceFixture(traceId) : null;
}

export function traceIdFromParam(param: string | null): TraceId {
  if (param === "clean") return "clean";
  if (param === "detour") return "detour";
  if (param === "late-failure") return "late-failure";
  return "late-failure";
}
